### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Test enhancement. Please see the latest [Travis build log](https://travis-ci.org/peter279k/urlify/builds/344363153).

### CODE REVIEW

**Comment by mmucklo** [comment]
Should I merge this yet?

**Comment by peter279k** [comment]
Maybe you can review the changes after merging the PR.

**Comment by mmucklo** [comment]
It looks like the tests lost their accented-characters.

They've been replaced with question-mark diamonds <?>...

**Comment by peter279k** [comment]
Because of the character encoding, I fix them in the latest commit.

**Comment by mmucklo** [comment]
ok, thanks!

**Pull request merged**
